//
// Created by Dan Schindler on 11/05/2022.
//

#ifndef FINDING_MINIMUM_SPANNING_TREE_VERTEXINADJACENTLIST_H
#define FINDING_MINIMUM_SPANNING_TREE_VERTEXINADJACENTLIST_H



class VertexInAdjacentList {

};



#endif //FINDING_MINIMUM_SPANNING_TREE_VERTEXINADJACENTLIST_H
